Add documentation on how to use built-in components
surface-ui/surface_site pull request #30
Opened 2021-04-24 13:10 UTC by imsekun

Hello this is to provide more help to beginners on how to use the built-in components. I got lost and wasn't sure how to use so I think this would be helpful.

2021-04-30 15:01 UTC, msaraiva reviewed
Hi @imsekun!

Thanks for the PR. I left a suggestion for your consideration.

2021-04-30 15:20 UTC, imsekun commented on lib/surface_site_web/live/builtin_components/index.ex
>        <#Markdown>
@msaraiva That's true. Since anyway there are already live examples for the components. I'll remove it.

2021-04-30 15:28 UTC, imsekun commented on lib/surface_site_web/live/builtin_components/index.ex
>        <#Markdown>
I ran into an error with the suggestion you gave. I'm not sure how to escape it.

`invalid location for heredoc terminator, please escape token or move it to its own line: """

![image](https://user-images.githubusercontent.com/20364796/116717700-b464f280-a9c8-11eb-8978-2e430076cdf2.png)
`

2021-05-02 08:02 UTC, Malian commented
@imsekun The example is still present ;)

Regarding the rebase, indeed something went wrong. The easiest way to proceed is

1. pull last changes from master locally (`git checkout master && git pull`)
2. rebase your branch on master (`git checkout your-branch && git rebase master`)
3. push your rebased branch (`git push --force`) <-- You will have to use the `force` option as you have modified the git history.

You should end with a pull request that contains only changes you have made. If you see changes that you did not make, it probably means something went wrong.

2021-05-02 08:59 UTC, imsekun commented
@Malian Alright give me a bit to figure this out. Time to me to explore.

2021-05-02 09:04 UTC, imsekun commented
Sweet! It worked. I just rebased it against `master` in this repo with `git rebase <REPO_ORIGIN> master`. Weird how GitHub doesn't automatically do this though.

2021-05-02 09:07 UTC, Malian requested changes
@imsekun just one last thing ;)

2021-05-02 09:07 UTC, Malian commented on lib/surface_site_web/live/builtin_components/index.ex
> +  alias SurfaceSiteWeb.Components.Code
This alias could also be removed.

2021-05-02 09:09 UTC, Malian commented
> Sweet! It worked. I just rebased it against `master` in this repo with `git rebase <REPO_ORIGIN> master`. Weird how GitHub doesn't automatically do this though.

It is indeed another way to do. The behaviour is perfectly normal as there are many use cases where you won't want to rebase.

I let a small comment about unused alias. Except that, LGTM.

2021-05-02 09:44 UTC, Malian approved these changes

2021-05-02 09:44 UTC, merged

2021-05-02 09:45 UTC, Malian commented
@imsekun Thanks! :heart: